"""

Revision ID: 59e8995d5ad2
Revises: 9e32eaec1fca
Create Date: 2025-02-20 16:50:06.336089

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "59e8995d5ad2"
down_revision = "9e32eaec1fca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("albums_album", sa.Column("cover_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "albums_album", "albums_image", ["cover_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_albums_album_cover", "albums_album", type_="foreignkey")
    op.drop_column("albums_album", "cover_id")
    # ### end Alembic commands ###
