"""

Revision ID: f85719eefc05
Revises: ffa61c9c9d0f
Create Date: 2025-02-21 11:47:08.903063

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "f85719eefc05"
down_revision = "ffa61c9c9d0f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "albums_album_category_title_key", "albums_album_category", type_="unique"
    )
    op.create_unique_constraint(None, "albums_album_category", ["author_id", "title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "albums_album_category", type_="unique")
    op.create_unique_constraint(
        "albums_album_category_title_key", "albums_album_category", ["title"]
    )
    # ### end Alembic commands ###
