"""

Revision ID: ffa61c9c9d0f
Revises: 59e8995d5ad2
Create Date: 2025-02-20 17:18:29.511547

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ffa61c9c9d0f"
down_revision = "59e8995d5ad2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "albums_album_image_position",
        sa.Column("video_id", sa.Integer(), nullable=False),
    )
    op.create_foreign_key(
        None,
        "albums_album_image_position",
        "albums_video",
        ["video_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "albums_album_image_position", type_="foreignkey")
    op.drop_column("albums_album_image_position", "video_id")
    # ### end Alembic commands ###
